[package]
name = "atme-service"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "atme_service"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.41"
entity = { path = "../entity" }
sea-orm = { workspace = true }
