//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "charge_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub start_timestamp: DateTimeWithTimeZone,
    pub end_timestamp: Option<DateTimeWithTimeZone>,
    pub start_percentage: i32,
    pub end_percentage: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
